### PR TITLE
update compatibility to reference 1.12

### PR DESCRIPTION
**Pull request by crunchyjohn**

### CODE REVIEW

**Comment by jknostman3** [comment]
@crunchyjohn Thanks! Should I update the PivNet release to list 1.11 and 1.12 in the dependencies of OpsMan and ERT?

**Comment by crunchyjohn** [comment]
@jknostman3 Please do.  I completely forgot about that-- thank you.

**Comment by jknostman3** [comment]
@crunchyjohn No problem. PivNet has now been updated.

**Comment by crunchyjohn** [comment]
Thank you!

**Pull request merged**
